using System.Collections;
using System.Collections.Generic;
using System.Linq;
using MemonPatta.Net;
using MemonPatta.Rules;
using Photon.Pun;
using TMPro;
using UnityEngine;
using UnityEngine.Events;
using UnityEngine.UI;

namespace MemonPatta.UI
{
    // Screen flow: Name -> Lobby (create / join by code / quick match) -> Room -> Game (+ round summary overlay).
    // The scene hierarchy is generated by Assets/Editor/GameSceneBuilder.cs; this class only fills it with data.
    public class GameUI : MonoBehaviour
    {
        [Header("Panels")]
        public GameObject panelName, panelLobby, panelRoom, panelGame, panelSummary;

        [Header("Name / lobby / room")]
        public TMP_InputField nameInput, codeInput;
        public Button connectBtn, createBtn, quickBtn, joinBtn, startBtn, leaveRoomBtn, backToNameBtn;
        public TMP_Text nameStatusText, lobbyHelloText, roomCodeText, roomPlayersText, roomHintText, startBtnText;

        [Header("Game")]
        public Button exitBtn, endMatchBtn, sortBtn, drawBtn, takeBtn, playBtn, extendBtn, discardBtn, finishBtn;
        public TMP_Text roundText, timerText, logText, drawCountText, takeBtnText;
        public RectTransform handContent, discardContent, meldsContent, playersContent;

        [Header("Summary")]
        public TMP_Text summaryTitle, summaryBody, summaryWaitText;
        public Button nextRoundBtn, summaryEndBtn, summaryCloseBtn;

        [Header("Misc")]
        public TMP_Text toastText;
        public CardSprites sprites;

        MatchNetwork net;
        ViewDto view;
        readonly HashSet<int> selected = new HashSet<int>();
        int selectedMeld = -1;
        int selectedDepth = -1;
        bool sortBySuit = true;
        bool matchOverShown;
        Coroutine toastRoutine;

        static readonly Color Gold = new Color(1f, 0.85f, 0.2f);
        static readonly Color Required = new Color(1f, 0.35f, 0.2f);
        static readonly Color PanelDark = new Color(0f, 0f, 0f, 0.35f);

        void Start()
        {
            net = MatchNetwork.Instance;
            if (net == null) { Debug.LogError("MatchNetwork is missing from the scene."); return; }

            net.StateChanged += OnStateChanged;
            net.RoomChanged += RefreshRoom;
            net.ViewChanged += OnView;
            net.Toast += ShowToast;
            net.MatchEnded += OnMatchEnded;

            Bind(connectBtn, OnConnect);
            Bind(backToNameBtn, net.Disconnect);
            Bind(createBtn, net.CreateRoom);
            Bind(quickBtn, net.QuickMatch);
            Bind(joinBtn, () => net.JoinRoom(codeInput.text));
            Bind(startBtn, net.StartMatch);
            Bind(leaveRoomBtn, net.LeaveRoom);

            Bind(exitBtn, net.LeaveRoom);
            Bind(endMatchBtn, net.EndMatch);
            Bind(sortBtn, () => { sortBySuit = !sortBySuit; Refresh(); });
            Bind(drawBtn, () => net.Draw());
            Bind(takeBtn, () => net.TakeDiscard(selectedDepth));
            Bind(playBtn, () => net.PlayMeld(selected.ToArray()));
            Bind(extendBtn, () => net.Extend(selectedMeld, selected.ToArray()));
            Bind(discardBtn, () => net.DiscardCard(selected.First()));
            Bind(finishBtn, () => net.Finish(view.hand[0]));
            Bind(nextRoundBtn, net.NextRound);
            Bind(summaryEndBtn, net.EndMatch);
            Bind(summaryCloseBtn, () => panelSummary.SetActive(false));

            nameInput.text = PlayerPrefs.GetString("playerName", "");
            toastText.transform.parent.gameObject.SetActive(false);
            OnStateChanged(net.State);
        }

        void OnDestroy()
        {
            if (net == null) return;
            net.StateChanged -= OnStateChanged;
            net.RoomChanged -= RefreshRoom;
            net.ViewChanged -= OnView;
            net.Toast -= ShowToast;
            net.MatchEnded -= OnMatchEnded;
        }

        static void Bind(Button b, UnityAction a) { if (b != null) b.onClick.AddListener(a); }

        void Update()
        {
            if (net != null && net.State == NetState.Room && net.BotCountdown >= 0 && roomHintText != null)
                roomHintText.text = "Waiting for players...\nBots join in " + Mathf.CeilToInt(net.BotCountdown) + "s";
            if (view == null || timerText == null) return;
            if (view.deadline > 0 && view.phase != 2)
            {
                int left = Mathf.Max(0, Mathf.CeilToInt((float)(view.deadline - PhotonNetwork.Time)));
                timerText.text = (left / 60) + ":" + (left % 60).ToString("00");
                timerText.color = left <= 15 ? Required : Color.white;
            }
            else timerText.text = "";
        }

        // ---- panels ----

        void OnConnect()
        {
            string n = nameInput.text.Trim();
            if (n.Length < 2) { nameStatusText.text = "Enter a name (2-16 characters)."; return; }
            if (n.Length > 16) n = n.Substring(0, 16);
            PlayerPrefs.SetString("playerName", n);
            nameStatusText.text = "";
            net.Connect(n);
        }

        void OnStateChanged(NetState s)
        {
            panelName.SetActive(s == NetState.Offline || s == NetState.Connecting);
            panelLobby.SetActive(s == NetState.Lobby);
            panelRoom.SetActive(s == NetState.Room);
            panelGame.SetActive(s == NetState.Playing);
            if (s != NetState.Playing) { panelSummary.SetActive(false); view = null; selected.Clear(); selectedMeld = -1; selectedDepth = -1; }
            connectBtn.interactable = s != NetState.Connecting;
            if (s == NetState.Connecting) nameStatusText.text = "Connecting...";
            else if (s == NetState.Offline && nameStatusText.text == "Connecting...") nameStatusText.text = "";
            if (s == NetState.Lobby) lobbyHelloText.text = "Hello, " + PhotonNetwork.NickName + "!";
            if (s == NetState.Room) RefreshRoom();
        }

        void RefreshRoom()
        {
            if (!PhotonNetwork.InRoom) return;
            roomCodeText.text = net.RoomCode;
            var players = PhotonNetwork.PlayerList;
            roomPlayersText.text = string.Join("\n", players.Select((p, i) =>
                (i + 1) + ". " + p.NickName + (p.IsMasterClient ? "  (Host)" : "") + (p.IsLocal ? "  (You)" : "")).ToArray())
                + "\n\n" + players.Length + " / " + MatchNetwork.MaxPlayers + " players";
            bool host = net.IsHost;
            startBtn.gameObject.SetActive(host);
            startBtn.interactable = players.Length >= 2;
            if (host && net.BotCountdown >= 0) return;   // Update() shows the bot countdown
            roomHintText.text = host
                ? (players.Length >= 2 ? "Everyone here? Start the match." : "Share the room code with friends. Need at least 2 players.")
                : "Waiting for the host to start the match...";
        }

        // ---- game rendering ----

        void OnView(ViewDto v)
        {
            view = v;
            if (view.hand != null) selected.RemoveWhere(c => !view.hand.Contains(c));
            if (!view.melds.Any(m => m.id == selectedMeld)) selectedMeld = -1;
            if (selectedDepth >= view.discard.Length) selectedDepth = -1;
            Refresh();
        }

        bool MyTurn { get { return view != null && view.activeActor == net.LocalActor; } }

        void Refresh()
        {
            if (view == null) return;
            bool roundOver = view.phase == 2;
            bool awaitDraw = MyTurn && view.phase == 0;
            bool playing = MyTurn && view.phase == 1;

            roundText.text = "Round " + view.round;
            var active = view.players.FirstOrDefault(p => p.actor == view.activeActor);
            string turnLine = MyTurn ? (view.phase == 0 ? "Your turn: draw a card." : "Your turn: play melds, then discard.")
                                     : (active != null ? active.name + "'s turn." : "");
            logText.text = roundOver ? view.log : turnLine + "\n" + view.log;
            drawCountText.text = view.drawCount.ToString();
            endMatchBtn.gameObject.SetActive(net.IsHost);

            RefreshPlayers();
            RefreshHand();
            RefreshDiscard();
            RefreshMelds();

            drawBtn.interactable = awaitDraw;
            takeBtn.gameObject.SetActive(awaitDraw && selectedDepth >= 0);
            if (selectedDepth >= 0) takeBtnText.text = "Take " + (selectedDepth + 1);
            playBtn.interactable = playing && selected.Count >= 3;
            extendBtn.interactable = playing && selected.Count >= 1 && selectedMeld >= 0;
            discardBtn.interactable = playing && selected.Count == 1 && view.hand.Length > 1;
            finishBtn.interactable = playing && view.hand.Length == 1 && view.required < 0;

            if (roundOver) ShowRoundSummary();
            else panelSummary.SetActive(false);
        }

        void RefreshPlayers()
        {
            Clear(playersContent);
            foreach (var p in view.players)
            {
                var tile = NewImage("Player", playersContent, p.actor == view.activeActor && view.phase != 2 ? new Color(0.15f, 0.55f, 0.25f, 0.9f) : PanelDark);
                var le = tile.gameObject.AddComponent<LayoutElement>();
                le.flexibleWidth = 1; le.preferredHeight = 120; le.minWidth = 120;
                var t = NewText(tile.transform, 22, TextAlignmentOptions.Center);
                Stretch(t.rectTransform, 4, 4);
                string me = p.actor == net.LocalActor ? " (You)" : "";
                t.text = "<b>" + p.name + me + "</b>\n" + p.handCount + " cards\n" + p.total + " pts" + (p.licensed ? "\n<color=#FFD633>Licensed</color>" : "");
            }
        }

        List<int> SortedHand()
        {
            var h = view.hand.ToList();
            return (sortBySuit ? h.OrderBy(Cards.Suit).ThenBy(Cards.Rank) : h.OrderBy(Cards.Rank).ThenBy(Cards.Suit)).ToList();
        }

        void RefreshHand()
        {
            Clear(handContent);
            foreach (int id in SortedHand())
            {
                int card = id;
                bool sel = selected.Contains(card);
                MakeCard(handContent, card, new Vector2(150, 216), () =>
                {
                    if (!selected.Add(card)) selected.Remove(card);
                    Refresh();
                }, sel ? Gold : (card == view.required ? Required : (Color?)null), sel ? 34 : 0);
            }
        }

        void RefreshDiscard()
        {
            Clear(discardContent);
            for (int i = 0; i < view.discard.Length; i++)
            {
                int index = i;
                int depth = view.discard.Length - 1 - i;
                bool inTake = selectedDepth >= 0 && depth <= selectedDepth;
                MakeCard(discardContent, view.discard[i], new Vector2(110, 160), () =>
                {
                    if (!(MyTurn && view.phase == 0)) { ShowToast("Draw from the pile or tap a discard on your turn."); return; }
                    selectedDepth = selectedDepth == depth ? -1 : depth;
                    Refresh();
                }, inTake ? Gold : (Color?)null, 0);
            }
            // Keep the top of the pile in view.
            Canvas.ForceUpdateCanvases();
            var sr = discardContent.GetComponentInParent<ScrollRect>();
            if (sr != null) sr.horizontalNormalizedPosition = 1f;
        }

        void RefreshMelds()
        {
            Clear(meldsContent);
            foreach (var m in view.melds)
            {
                int id = m.id;
                bool sel = selectedMeld == id;
                var row = NewImage("Meld", meldsContent, sel ? new Color(0.9f, 0.75f, 0.1f, 0.5f) : PanelDark);
                var le = row.gameObject.AddComponent<LayoutElement>();
                le.preferredHeight = 150;
                var btn = row.gameObject.AddComponent<Button>();
                btn.transition = Selectable.Transition.None;
                btn.onClick.AddListener(() => { selectedMeld = selectedMeld == id ? -1 : id; Refresh(); });

                var owner = view.players.FirstOrDefault(p => p.actor == m.owner);
                var label = NewText(row.transform, 22, TextAlignmentOptions.Left);
                var lr = label.rectTransform;
                lr.anchorMin = new Vector2(0, 0); lr.anchorMax = new Vector2(0, 1);
                lr.pivot = new Vector2(0, 0.5f); lr.offsetMin = new Vector2(12, 0); lr.sizeDelta = new Vector2(170, 0);
                label.text = "<b>" + (owner != null ? owner.name : "?") + "</b>\n" + (m.isRun ? "Run" : "Set") + " (" + m.cards.Length + ")";

                var holder = new GameObject("Cards", typeof(RectTransform)).GetComponent<RectTransform>();
                holder.SetParent(row.transform, false);
                holder.anchorMin = new Vector2(0, 0); holder.anchorMax = new Vector2(1, 1);
                holder.offsetMin = new Vector2(190, 6); holder.offsetMax = new Vector2(-8, -6);
                var h = holder.gameObject.AddComponent<HorizontalLayoutGroup>();
                h.spacing = -48; h.childAlignment = TextAnchor.MiddleLeft;
                h.childControlWidth = true; h.childControlHeight = true; h.childForceExpandWidth = false; h.childForceExpandHeight = false;
                foreach (int c in m.cards) MakeCard(holder, c, new Vector2(90, 130), null, null, 0);
            }
        }

        GameObject MakeCard(Transform parent, int cardId, Vector2 size, UnityAction onClick, Color? outline, float lift)
        {
            var slot = new GameObject("Card " + cardId, typeof(RectTransform)).GetComponent<RectTransform>();
            slot.SetParent(parent, false);
            var le = slot.gameObject.AddComponent<LayoutElement>();
            le.preferredWidth = size.x; le.preferredHeight = size.y;

            var img = NewImage("Face", slot, Color.white);
            img.sprite = sprites != null ? sprites.Get(cardId) : null;
            img.preserveAspect = true;
            var rt = img.rectTransform;
            rt.anchorMin = Vector2.zero; rt.anchorMax = Vector2.one;
            rt.offsetMin = new Vector2(0, lift); rt.offsetMax = new Vector2(0, lift);
            if (outline.HasValue)
            {
                var o = img.gameObject.AddComponent<Outline>();
                o.effectColor = outline.Value;
                o.effectDistance = new Vector2(5, -5);
            }
            if (onClick != null)
            {
                var b = img.gameObject.AddComponent<Button>();
                b.transition = Selectable.Transition.None;
                b.onClick.AddListener(onClick);
            }
            return slot.gameObject;
        }

        // ---- summary ----

        void ShowRoundSummary()
        {
            var winner = view.players.FirstOrDefault(p => p.actor == view.winner);
            summaryTitle.text = "Round " + view.round + " complete";
            summaryBody.text = (winner != null ? "<b>" + winner.name + " wins the round!</b>\n\n" : "") + string.Join("\n\n",
                view.players.OrderByDescending(p => p.roundScore).Select(p =>
                    "<b>" + p.name + "</b>" + (p.actor == view.winner ? "  x10" : "  x5") + "\n" +
                    "played " + p.played + " - left " + p.remaining + " = " + p.baseScore + "  ->  <b>" + p.roundScore + "</b>   (total " + p.total + ")").ToArray());
            bool host = net.IsHost;
            nextRoundBtn.gameObject.SetActive(host);
            summaryEndBtn.gameObject.SetActive(host);
            summaryCloseBtn.gameObject.SetActive(false);
            summaryWaitText.gameObject.SetActive(!host);
            panelSummary.SetActive(true);
        }

        void OnMatchEnded(string standings)
        {
            // Show the final standings over whichever panel is active (the room panel after the match).
            summaryTitle.text = "Match over";
            summaryBody.text = standings;
            nextRoundBtn.gameObject.SetActive(false);
            summaryEndBtn.gameObject.SetActive(false);
            summaryWaitText.gameObject.SetActive(false);
            summaryCloseBtn.gameObject.SetActive(true);
            panelSummary.SetActive(true);
            panelSummary.transform.SetAsLastSibling();
            RefreshRoom();
        }

        // ---- toast ----

        void ShowToast(string msg)
        {
            if (toastText == null) return;
            toastText.text = msg;
            toastText.transform.parent.gameObject.SetActive(true);
            toastText.transform.parent.SetAsLastSibling();
            if (toastRoutine != null) StopCoroutine(toastRoutine);
            toastRoutine = StartCoroutine(HideToast());
            if (nameStatusText != null && panelName.activeInHierarchy && net.State != NetState.Connecting) nameStatusText.text = msg;
        }

        IEnumerator HideToast()
        {
            yield return new WaitForSeconds(3f);
            toastText.transform.parent.gameObject.SetActive(false);
        }

        // ---- tiny UI helpers ----

        static void Clear(Transform t)
        {
            for (int i = t.childCount - 1; i >= 0; i--)
            {
                var child = t.GetChild(i);
                child.SetParent(null);   // Destroy is deferred; detach so layouts and counts update immediately
                Destroy(child.gameObject);
            }
        }

        static Image NewImage(string name, Transform parent, Color color)
        {
            var go = new GameObject(name, typeof(RectTransform), typeof(CanvasRenderer), typeof(Image));
            go.transform.SetParent(parent, false);
            var img = go.GetComponent<Image>();
            img.color = color;
            return img;
        }

        static TMP_Text NewText(Transform parent, float size, TextAlignmentOptions align)
        {
            var go = new GameObject("Text", typeof(RectTransform), typeof(CanvasRenderer), typeof(TextMeshProUGUI));
            go.transform.SetParent(parent, false);
            var t = go.GetComponent<TextMeshProUGUI>();
            t.fontSize = size; t.alignment = align; t.color = Color.white; t.raycastTarget = false;
            return t;
        }

        static void Stretch(RectTransform rt, float h, float v)
        {
            rt.anchorMin = Vector2.zero; rt.anchorMax = Vector2.one;
            rt.offsetMin = new Vector2(h, v); rt.offsetMax = new Vector2(-h, -v);
        }
    }
}
